### ISSUE TITLE
Update to Androidx

### ISSUE THREAD

**Issue by quiro91** [blueshift-labs/Blueshift-Android-SDK#102]
Hey everyone,

is there any plan to release an Androidx version? It's one of the very few sdk I'm missing to be able to remove Jetifier

**Comment by aswani521** [comment]
hey @quiro91 we are looking into this, in the meantime, would be able to open a support ticket from your work email?

**Comment by quiro91** [comment]
I did. By the way, do you accept contributions about it?

**Comment by rahulrvp** [comment]
Hi @quiro91, we have released the AndroidX version of our SDK, please check the email from our support to know more.
