### ISSUE TITLE
Upgrade Firebase Core dependency

### ISSUE THREAD

**Issue by droidizer** [blueshift-labs/Blueshift-Android-SDK#138]
Hello, 
I see that the firebase core dependency is not up to date and causes issue in the builds. 
Would be great if you could upgrade.

    compile 'com.google.firebase:firebase-core:16.0.6'

Thanks.

**Comment by rahulrvp** [comment]
Thanks for reporting this issue.
We're working on our dependency upgrade. Please follow the releases page for updates.

if you are blocked on this, please [exclude](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:excluding-transitive-deps) the firebase-core dependency coming from our SDK.

**Comment by droidizer** [comment]
Please check my Zendesk Ticket for follow up issue.

From email : sgu@amboss.com

Your request (11912) has been received and is being reviewed by our support
staff.

Best,
Sowmya

**Comment by rahulrvp** [comment]
Thanks for filing a support ticket. We will followup in Zendesk.

**Comment by rahulrvp** [comment]
Closing the ticket as the support ticket is closed.
