### ISSUE TITLE
App crash when using firebase versions as suggested in documentation

### ISSUE THREAD

**Issue by HughIngram** [blueshift-labs/Blueshift-Android-SDK#178]
In the documentation, it is suggested to use these versions of Firebase sdk:
```
    implementation 'com.google.firebase:firebase-core:17.2.0'
    implementation 'com.google.firebase:firebase-messaging:20.0.0'
```

https://developer.blueshift.com/docs/setup-blueshifts-android-sdk

This led to an app crash for our application. After a fresh install, the app would crash on first launch. The app did not crash on subsequent launches. The crash could be re-created consistently on July 31st, but we can no longer re-create it as of August 5th.

This crash was only reported after we launched an inapp campaign on July 27th.

We are using Blueshift sdk version `3.1.2`.

<details>
<summary>Example crash report</summary>

```
Fatal Exception: java.lang.RuntimeException
Unable to bind to service com.blueshift.fcm.BlueshiftMessagingService@43fa0ce with Intent { act=com.google.firebase.MESSAGING_EVENT pkg=de.miamed.amboss.knowledge }: java.lang.NullPointerException
android.app.ActivityThread.handleBindService (ActivityThread.java:4234)
android.app.ActivityThread.access$1600 (ActivityThread.java:237)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1937)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:223)
android.app.ActivityThread.main (ActivityThread.java:7656)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:592)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:947)
```

```
Caused by java.lang.NullPointerException
android.app.ActivityThread.handleBindService

com.google.firebase.messaging.zzc.onBind (zzc.java:3)
android.app.ActivityThread.handleBindService (ActivityThread.java:4219)
android.app.ActivityThread.access$1600 (ActivityThread.java:237)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1937)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:223)
android.app.ActivityThread.main (ActivityThread.java:7656)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:592)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:947)
```

</details>

We fixed the crash by upgrading to these versions:
```
    implementation 'com.google.firebase:firebase-core:17.4.4'
    implementation 'com.google.firebase:firebase-messaging:20.2.4'
```

We would recommend to update the documentation to suggest more recent versions of the Firebase sdk.

**Comment by rahulrvp** [comment]
Hi @HughIngram. thanks for reporting this issue. We will make the necessary edits to our docs.

**Comment by rahulrvp** [comment]
Hi @HughIngram We have fixed the documentation by adding the latest firebase library versions. Thanks again for reporting.

Please note that the app is free to use any version of the FCM/Core SDKs. Since Blueshift Android SDK uses FCM for push, you might see crashes inside the SDK if there is an issue with Firebase libraries used.
