### ISSUE TITLE
Androidx migration

### ISSUE THREAD

**Issue by HughIngram** [blueshift-labs/Blueshift-Android-SDK#228]
I'm using the latest version of the Blueshift sdk (3.1.8); according to the relase notes this is migrated to androidx. But I can not remove jetifier from my project due to Blueshift's dependency on `com.android.support:appcompat-v7:28.0.0`

I checked with the tool "CanIDropJetifier" - https://github.com/plnice/can-i-drop-jetifier

With the command `./gradlew -Pandroid.enableJetifier=false my-module:canIDropJetifier`, and `verbose=true` in its configuration, I got this result:

```
Cannot drop Jetifier due to following external dependencies:

* com.blueshift:android-sdk:3.1.8
  \-- com.android.support:appcompat-v7:28.0.0

```

It looks like there is still a dependency to the support library here also:
https://github.com/blueshift-labs/Blueshift-Android-SDK/blob/main/android-sdk/build.gradle#L49

related issue:
https://github.com/blueshift-labs/Blueshift-Android-SDK/issues/102

**Comment by rahulrvp** [comment]
Hello @HughIngram. Thanks for reporting this issue.

Could you please confirm if you are using the AndroidX version of the v3.1.8 of our SDK? The artifact name is `android-sdk-x`. You should have something like this in your `build.gradle` file.

```
implementation 'com.blueshift:android-sdk-x:3.1.8'
```

In this version, we are using the `appcompat` libs that belong to the `androidx` package. [source](https://github.com/blueshift-labs/Blueshift-Android-SDK/blob/main_androidx/android-sdk/build.gradle#L48)

**Comment by HughIngram** [comment]
Thanks Rahul, I was using 'com.blueshift:android-sdk:3.1.8' - I didn't realise that this new artifact was available :smile:
