### ISSUE TITLE
Latest release not available for `android-sdk-x`

### ISSUE THREAD

**Issue by WBertan** [blueshift-labs/Blueshift-Android-SDK#255]
Can't find the release `3.2.0.1` for `android-sdk-x`.

On this topic, isn't the first time I see a new release done for `android-sdk` but having some delay to be available for `android-sdk-x`.

What would be an "expected" reasonable delay for a new version to be available for `android-sdk-x`?

**Comment by rahulrvp** [comment]
Hi, @WBertan thanks for reaching out.

The usual delay between two releases is 2 days to a week maximum.

3.2.0.1 was a hotfix release we made for a specific customer for a specific issue. We decided to release this same change with our next major release to our AndroidX version. Please let us know if you are blocked on this, we can try to prioritize this in that case.

**Comment by WBertan** [comment]
Thanks, we are not blocked, we can wait for the next major release without a problem.
