### ISSUE TITLE
Dead lock in RequestQueue.java

### ISSUE THREAD

**Issue by ducgao** [blueshift-labs/Blueshift-Android-SDK#258]
I found a problem.
If something happend that make the RequestDispatcher can not create/get the Handler, the dispatcher will invoke complete without makeQueueAvailable -> that's make every request behind will stuck.

In my case, whenever I set pushEnable to false, the problem appear.

**Comment by rahulrvp** [comment]
Hi @ducgao Thanks for reporting the issue.

We recently identified the issue and a fix is being evaluated at the moment. This should go out in our upcoming release.

**Comment by rahulrvp** [comment]
@ducgao this issue is fixed in [v3.2.1](https://github.com/blueshift-labs/Blueshift-Android-SDK/releases/tag/v3.2.1)
