### ISSUE TITLE
Click on notification make activity destroy then recreate instead of bring the old one to front

### ISSUE THREAD

**Issue by ducgao** [blueshift-labs/Blueshift-Android-SDK#261]
On class NotificationFactoty.java, function getNotificationClickPendingIntent, I found the problem here, because of TaskStackBuilder's behaviour, whenever user tap on a notification, app will destroy current activity and recreate the same activity instead of bring the existing one to front of activity's stack.

That behaviour will make so much inconvenience for user.
My suggestion is using regular Pending Intent instead of make a PendingIntent from TaskStackBuilder. Or atleast make that configurable

**Comment by rahulrvp** [comment]
Thanks for the feedback @ducgao. We will review this with the team.

**Comment by rahulrvp** [comment]
We have implemented this change in our recent release ([v3.4.3](https://github.com/blueshift-labs/Blueshift-Android-SDK/releases/tag/v3.4.3)). We are bringing the host app's main activity to the foreground when launching a URL from push notifications, if the activity is present in the stack.
