### ISSUE TITLE
Android 12 support

### ISSUE THREAD

**Issue by gaurav-girish** [blueshift-labs/Blueshift-Android-SDK#273]
While migrating our app to target Android 12 (Api 31) all activities and broadcast receivers need to have the 'exported' tag set. This also applies to the merged manifest. Could you folks tag all your activity and broadcast receivers with this info. This saves us from a messy manifest where we have to manually merge the manifest for you with those tags.

Android reference:
https://developer.android.com/about/versions/12/behavior-changes-12#exported

This is the current workaround:
https://developer.android.com/studio/build/manifest-merge

**Comment by rahulrvp** [comment]
Hi @gaurav-girish, Thanks for reporting the issue!

We are actively working on making the SDK compatible with Android 12. Keep an eye on the release page to get updates regarding the release of the same.

**Comment by rahulrvp** [comment]
Hi @gaurav-girish, we have enabled Android 12 support in [v3.2.3](https://github.com/blueshift-labs/Blueshift-Android-SDK/releases/tag/v3.2.3). Please update and let us know your feedback.
