### ISSUE TITLE
Implicit PendingIntent Vulnerability

### ISSUE THREAD

**Issue by stormgain-dev** [blueshift-labs/Blueshift-Android-SDK#294]
Hello,

Google Play Console reports a security issue originating from the method [`scheduleNotifications`](https://github.com/blueshift-labs/Blueshift-Android-SDK/blob/598ab4bca32a413fa4c9b5fd481ce6012d558c7e/android-sdk/src/main/java/com/blueshift/rich_push/NotificationFactory.java#L249)

> ## Security and trust
> ### Implicit pending intent
> Your app contains an implicit pending intent vulnerability. Please see [this Google Help Centre article](https://support.google.com/faqs/answer/10437428) for details.
> - com.blueshift.rich_push.NotificationFactory.scheduleNotifications

Although the issue doesn’t block publication of the apps, it would be good to fix it anyway. Please, also apply the fix to the [Codrova plugin](https://github.com/blueshift-labs/Blueshift-Cordova-Plugin) as well. Thanks!

**Comment by rahulrvp** [comment]
@stormgain-dev thanks for reporting the issue with the details. We will add a ticket for this and keep you updated once the fix goes out. Please send an email to support@blueshift.com next time for fast assistance.

**Comment by rahulrvp** [comment]
Hello @stormgain-dev, we have added this fix in our [recent release](https://github.com/blueshift-labs/Blueshift-Android-SDK/releases/tag/v3.2.8-beta.1). The Cordova plugin will be updated in a couple of days.

**Comment by stormgain-dev** [comment]
Thank you

**Comment by rahulrvp** [comment]
@stormgain-dev Cordova plugin [v0.0.3](https://github.com/blueshift-labs/Blueshift-Cordova-Plugin/releases/tag/0.0.3) is released!
