### ISSUE TITLE
Update com.google.firebase:firebase-messaging

### ISSUE THREAD

**Issue by guillaumewrobel** [blueshift-labs/Blueshift-Android-SDK#339]
Version [23.2.1](https://mvnrepository.com/artifact/com.google.firebase/firebase-messaging/23.2.1) is available

**Comment by rahulrvp** [comment]
@guillaumewrobel thanks for reaching out. The Firebase version in the SDK is the minimum version supported by us. The host app can use the latest version by adding a dependency in the `build.gradle` file.

If you have any more questions, please feel free to drop an email to support@blueshift.com.
