### ISSUE TITLE
Crashes in 4.0.0

### ISSUE THREAD

**Issue by FredrikKarakerNx** [blueshift-labs/Blueshift-Android-SDK#364]
Hi,

We have discovered two crashes in production since bumping to 4.0.0. They both happen inside the identifyUser() method and occurs on various android versions and devices.

![Skärmavbild 2024-11-25 kl  09 14 21](https://github.com/user-attachments/assets/748e9ffe-4163-4600-90e2-3496826a43ce)
![Skärmavbild 2024-11-25 kl  09 14 58](https://github.com/user-attachments/assets/9eff216b-4cce-4b8f-994c-96549895f0fa)

**Comment by rahulrvp** [comment]
@FredrikKarakerNx Thank you for reporting the issue to us.

Please email us at support@blueshift.com with the complete crash logs. We will review them and get back to you.
