### ISSUE TITLE
Crash bug in GCMIntentService

### ISSUE THREAD

**Issue by justincpollard** [blueshift-labs/Blueshift-Android-SDK#56]
Hi,

I'm using v1.0.5 of the Blueshift SDK in my app. I've seen a crash bug, so wanted to alert you all (sorry about the stacktrace screenshot; I'm on my phone, so that was easiest)
![screenshot_20170610-104459](https://user-images.githubusercontent.com/1743546/27005032-3b77d35a-4dca-11e7-9bd9-7091f98b08fc.png)

**Comment by rahulrvp** [comment]
We have fixed the issue and released a new version (v1.0.6). Please use the lastest version and let us know your feedback.

Thanks.

**Comment by justincpollard** [comment]
Thanks!
