### ISSUE TITLE
Permissions ACCESS_FINE_LOCATION

### ISSUE THREAD

**Issue by hayribakici** [blueshift-labs/Blueshift-Android-SDK#67]
Hi,

thank you for the nice library. It would be nice to document, that the `ACCESS_FINE_LOCATION` permission is optional, because as a user myself, it would creep me out to see that an app wants location permissions, even when the app is a simple content app.

Thank you very much! :)
cheers

**Comment by rahulrvp** [comment]
Thanks for the feedback @hayribakici.

In our docs, we have mentioned that the location permission taken for the analytical purpose is optional.
