### ISSUE TITLE
getAdvertisingID() method should run in background

### ISSUE THREAD

**Issue by swarna-sathya** [blueshift-labs/Blueshift-Android-SDK#89]
The method to fetch Android Advertising ID in class `DeviceUtils` should run in the background thread.
> Note: The getAdvertisingIdInfo() method is a blocking call, so you must not call it on the main (UI) thread. If called on the main thread, the method throws IllegalStateException.

You can find the above note [here](http://www.androiddocs.com/google/play-services/id.html)

Since IllegalStateException is thrown, the following catch block is getting executed:

```
catch (IllegalStateException | GooglePlayServicesNotAvailableException var6) {
            Log.e(LOG_TAG, libNotFoundMessage);
            installNewGooglePlayServicesApp(context);
}
```
It is trying to install Google Play Services although it is present and take the user to Google Play Store. This navigation is highly undesirable. Can this be fixed, please?

**Comment by rahulrvp** [comment]
Hi Swarna,

The `getAdvertisingID()` is a wrapper around `AdvertisingIdClient.getAdvertisingIdInfo(context)` method call. Which can not be called from main thread. For the same reason, you should not call `getAdvertisingID()` from the main thread. Please call it from a non-UI thread followed by the identify call.

**Comment by swarna-sathya** [comment]
Thanks, Rahul.

I also realized that the `SendEventTask` is implemented to call `sendEvent()`, so eventually, the consequent methods will be called in the background thread. Sorry about the inconvenience.

**Comment by rahulrvp** [comment]
No worries. Hope you are unblocked on this now. Going ahead and closing the ticket.
