### ISSUE TITLE
Push notification issues on Samsung devices

### ISSUE THREAD

**Issue by ahampe** [blueshift-labs/Blueshift-Android-SDK#98]
Some push notifications do not work properly on Samsung devices. I can't reproduce these issues on Google Pixels or devices from other manufacturers. The notification padding is too small, background does not match other notifications, images don't load, and deep links don't work: although the app opens, no deep link is being passed to the extras bundle received in the activity.
On phone (Galaxy S8, first notification is from Blueshift):
![Screenshot_20191007-130006_Gallery](https://user-images.githubusercontent.com/26446893/66351443-6a15af80-e912-11e9-813c-e90bf606db72.jpg)
On tablet (Galaxy Tab A, two notifications from Blueshift):
<img width="480" alt="Screen Shot 2019-10-07 at 2 49 21 PM" src="https://user-images.githubusercontent.com/26446893/66351060-b7455180-e911-11e9-9054-ced3dfbcfd35.png">

**Comment by aswani521** [comment]
@ahampe thanks for reporting we will take a look at these issues.

**Comment by rahulrvp** [comment]
Hi Alex, we are closing this issue here in GitHub for now. Please email us at support@blueshift.com if you are still facing this issue.
